# Generated by Django 3.0.5 on 2020-04-14 13:50

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_category_comment_cover_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(default=0, verbose_name='内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, default='null', verbose_name='内容'),
        ),
    ]
