# Generated by Django 3.0.5 on 2020-04-12 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User2',
        ),
    ]
