# Generated by Django 3.0.5 on 2020-04-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='shanghai', max_length=80),
        ),
    ]
